#!/bin/sh

REMOTE=$1

LS_REMOTE=ls_remote_tmp
ssh $REMOTE ls -l /root/midi2note | tail -n +2 > $LS_REMOTE
LS_LOCAL=ls_local_tmp
ls -l /root/midi2note/remote_compute | tail -n +2 > $LS_LOCAL

diff_before=`diff -b $LS_LOCAL $LS_REMOTE | grep "<"`
diff_after=`diff -b $LS_LOCAL $LS_REMOTE | grep ">"`

if [ "${diff_after}" = "" ] ; then
  echo "no new file on remote."
else
  echo "remote (source):"
  echo "${diff_after}"
  echo "local (destination):"
  echo "${diff_before}"

  echo -n "OK?(y/n):"
  read answer
  case $answer in
    y)
        for line in "${diff_after}" ; do
          filename=`echo "$line" | awk '{ print $11 }'`
          scp -p $REMOTE:/root/midi2note/$filename /root/midi2note/remote_compute/
        done 
        ;;
    *)
        ;;
  esac
fi

rm -f $LS_REMOTE 
rm -f $LS_LOCAL 

exit 0
