#!/bin/sh

REMOTE=$1

LS_REMOTE=ls_remote_tmp
ssh $REMOTE ls -l --time-style=iso /root/midi2note | tail -n +2 > $LS_REMOTE
LS_LOCAL=ls_local_tmp
ls -l --time-style=iso /root/midi2note/remote_compute | tail -n +2 > $LS_LOCAL

diff_before=`diff -b $LS_REMOTE $LS_LOCAL | grep "<"`
diff_after=`diff -b $LS_REMOTE $LS_LOCAL | grep ">"`

if [ "${diff_after}" = "" ] ; then
  echo "no new file on local."
else
  echo "local (source):"
  echo "${diff_after}"
  echo "remote (destination):"
  echo "${diff_before}"

  echo -n "OK?(y/n):"
  read answer
  case $answer in
    y)
        for line in "${diff_after}" ; do
          filename=`echo "$line" | awk '{ print $9 }'`
          scp -p /root/midi2note/remote_compute/$filename $REMOTE:/root/midi2note/
        done 
        ;;
    *)
        ;;
  esac
fi

rm -f $LS_REMOTE 
rm -f $LS_LOCAL 

exit 0
